OOD_HARD = [
    # ==== GENERAL KNOWLEDGE / TRIVIA ====
    r"\bwhat\s+is\b",
    r"\bwho\s+is\b",
    r"\bwhere\s+is\b",
    r"\bwhen\s+is\b",
    r"\bwhy\s+is\b",
    r"\bhow\s+(?:do|does|did|to|can|many|much|far|long)\b",
    r"\bdefine\b",
    r"\bdefinition\b",
    r"\bexplain\b",
    r"\btrivia\b",
    r"\bfacts?\b",
    r"\bfun\s+fact(s)?\b",
    r"\bbiograph(?:y|ies)\b",
    r"\bsummary\s+of\s+(?:history|country|city|language|religion)\b",

    # ==== GEOGRAPHY / POLITICAL TRIVIA ====
    r"\bcapital(s)?\b",
    r"\bpopulation(s)?\b",
    r"\bcontinent(s)?\b",
    r"\bcountry\b",
    r"\bcountries\b",
    r"\bprovince(s)?\b",
    r"\bstate(s)?\b",
    r"\bcounty\b",
    r"\bcity\b",
    r"\btown\b",
    r"\btimezone(s)?\b",
    r"\btime\s+in\s+\w+",
    r"\bmap(?:s)?\b",
    r"\bflag(s)?\b",
    r"\bborder(s)?\b",
    r"\blanguage(s)?\b",
    r"\bofficial\s+language(s)?\b",

    # ==== WEATHER / ASTRONOMY / EARTH SCIENCE ====
    r"\bweather\b",
    r"\bforecast\b",
    r"\btemperature\b",
    r"\brainfall\b",
    r"\bhumidity\b",
    r"\bwind\s+speed\b",
    r"\bsunrise\b",
    r"\bsunset\b",
    r"\bmoon\s+phase\b",
    r"\beclipse\b",
    r"\bsolstice\b",
    r"\bequinox\b",

    # ==== UNITS / CONVERSIONS ====
    r"\bconvert(ing|ed|s)?\b",
    r"\bconversion(s)?\b",
    r"\bhow\s+many\s+(?:meters|metres|kilometers|miles|feet|inches|pounds|kilograms)\b",
    r"\b(c|f)\s*°?\b",
    r"\b°\s*(c|f)\b",
    r"\bkm\b",
    r"\bmi\b",
    r"\bkg\b",
    r"\blb(s)?\b",
    r"\bcm\b",
    r"\bmm\b",

    # ==== MATH / CALCULATION ====
    r"\bcalculate\b",
    r"\bcalculation\b",
    r"\bsum\b",
    r"\bproduct\b",
    r"\bdifference\b",
    r"\bquotient\b",
    r"\bequation(s)?\b",
    r"\bsolve\b",
    r"\bcompute\b",
    r"\bintegral(s)?\b",
    r"\bderivative(s)?\b",
    r"\balgebra\b",
    r"\bgeometry\b",
    r"\btrigonometry\b",
    r"\bcalculus\b",
    r"\bmatrix\b",
    r"\bprobabilit(y|ies)\b",
    r"\bstatistic(s)?\b",
    r"\bmean\b",
    r"\bmedian\b",
    r"\bmode\b",
    r"\bvariance\b",
    r"\bstandard\s+deviation\b",
    r"\bprime(s)?\b",
    r"\bfactor(s|ization)?\b",
    r"\bmodulo\b",
    r"\bpercentage\b",
    r"\bpercent\b",

    # ==== PROGRAMMING / CODING / TECH SUPPORT ====
    r"\bcode\b",
    r"\bcoding\b",
    r"\bprogram\b",
    r"\bprogramming\b",
    r"\bsnippet\b",
    r"\bscript\b",
    r"\balgorithm\b",
    r"\bdebug(ger|ging)?\b",
    r"\berror\s+message\b",
    r"\bstack\s*trace\b",
    r"\bapi\b",
    r"\bendpoint\b",
    r"\bhttp\b",
    r"\bjson\b",
    r"\bxml\b",
    r"\byaml\b",
    r"\bmarkdown\b",
    r"\bregex\b",
    r"\bpython\b",
    r"\bjava(script)?\b",
    r"\btypescript\b",
    r"\bc\+\+\b",
    r"\bc#\b",
    r"\bgo(lang)?\b",
    r"\brust\b",
    r"\bphp\b",
    r"\bruby\b",
    r"\bsql\b",
    r"\bscala\b",
    r"\bkotlin\b",
    r"\bswift\b",
    r"\bdocker\b",
    r"\bkubernetes\b",
    r"\blinux\b",
    r"\bwindows\b",
    r"\bmac\s?os\b",
    r"\bubuntu\b",
    r"\binstall\b",
    r"\bbuild\b",
    r"\bcompile\b",
    r"\bpackage\b",
    r"\bdependency\b",
    r"\bvenv\b",
    r"\brequirements\.txt\b",
    r"\bvirtualenv\b",
    r"\bgit\b",
    r"\bgithub\b",
    r"\bgitlab\b",
    r"\bbitbucket\b",
    r"\bci/cd\b",

    # ==== INTERNET / BROWSING / SEARCH ====
    r"\bgoogle\b",
    r"\bbing\b",
    r"\bsearch\b",
    r"\blink\b",
    r"\burl\b",
    r"\bwebsite\b",
    r"\bweb\s*page\b",
    r"\bdownload\b",
    r"\bupload\b",

    # ==== TIME / DATES / SCHEDULING ====
    r"\bcurrent\s+time\b",
    r"\bwhat\s+time\s+is\s+it\b",
    r"\btoday('?s)?\s+date\b",
    r"\bcalendar\b",
    r"\bschedule\b",
    r"\bevent(s)?\b",
    r"\bdeadline\b",
    r"\bremind\b",

    # ==== CURRENCY / FINANCE / ECONOMICS ====
    r"\bexchange\s+rate(s)?\b",
    r"\bforex\b",
    r"\bcurrency\b",
    r"\bhow\s+much\s+is\b",
    r"\bconvert\s+\d+(\.\d+)?\s*(usd|eur|gbp|ron|lei|jpy|cny|cad|aud|chf|sek|nok|dkk|inr|brl|zar)\s+(?:to|in)\s*(usd|eur|gbp|ron|lei|jpy|cny|cad|aud|chf|sek|nok|dkk|inr|brl|zar)\b",
    r"\bprice(s)?\b",
    r"\bcost\b",
    r"\bhow\s+much\b",
    r"\b\$|\€|£|¥|₹",
    r"\busd\b",
    r"\beur\b",
    r"\bgbp\b",
    r"\brub\b",
    r"\bron\b",
    r"\blei\b",
    r"\bjpy\b",
    r"\bcny\b",
    r"\bcad\b",
    r"\baud\b",
    r"\bchf\b",
    r"\bsek\b",
    r"\bnok\b",
    r"\bdkk\b",
    r"\binr\b",
    r"\bbrl\b",
    r"\bzar\b",
    r"\bstock(s)?\b",
    r"\bindex\b",
    r"\betf(s)?\b",
    r"\bcrypto\b",
    r"\bbitcoin\b",
    r"\beth(?:ereum)?\b",
    r"\bdoge(?:coin)?\b",
    r"\bmarket\b",
    r"\bportfolio\b",
    r"\bprofit\b",
    r"\bloss\b",
    r"\binterest\s+rate(s)?\b",
    r"\binflation\b",
    r"\bgdp\b",
    r"\bunemployment\b",
    r"\btax(es)?\b",
    r"\bvat\b",
    r"\binvoice\b",
    r"\bbilling\b",
    r"\bsubscription\b",

    # ==== SHOPPING / DEALS ====
    r"\bdiscount(s)?\b",
    r"\bdeal(s)?\b",
    r"\bpromo(code|tion)?\b",
    r"\bbuy\b",
    r"\bpurchase\b",
    r"\border\b",
    r"\bcheckout\b",
    r"\bcart\b",

    # ==== SPORTS / SCORES / FIXTURES ====
    r"\bscore(s)?\b",
    r"\bfixture(s)?\b",
    r"\bmatch(es)?\b",
    r"\bgame(s)?\b",
    r"\bleague\b",
    r"\btournament\b",
    r"\bstandings\b",
    r"\btable\b",
    r"\btransfer(s)?\b",
    r"\bdraft\b",
    r"\bodds\b",
    r"\bbet(ting)?\b",

    # ==== ENTERTAINMENT (NON-BOOK META) ====
    r"\bmovie(s)?\b",
    r"\bfilm(s)?\b",
    r"\btv\s*show(s)?\b",
    r"\bseries\b",
    r"\bepisode(s)?\b",
    r"\bseason(s)?\b",
    r"\bbest\s+movies\b",
    r"\bbox\s+office\b",
    r"\bimdb\b",
    r"\brotte?n\s+tomatoes\b",
    r"\bnetflix\b",
    r"\bhbo\b",
    r"\bprime\s+video\b",
    r"\bdisney\+\b",
    r"\bspotify\b",
    r"\bmusic\b",
    r"\balbum(s)?\b",
    r"\bsong(s)?\b",
    r"\blyric(s)?\b",
    r"\bconcert(s)?\b",
    r"\bartist(s)?\b",

    # ==== NEWS / POLITICS / CURRENT EVENTS ====
    r"\bbreaking\s+news\b",
    r"\bheadline(s)?\b",
    r"\bnews\b",
    r"\belection(s)?\b",
    r"\bvote(s|ing)?\b",
    r"\bpolitic(s|al)\b",
    r"\bminister\b",
    r"\bpresident\b",
    r"\bprime\s+minister\b",
    r"\bcabinet\b",
    r"\bparliament\b",
    r"\bdiplomacy\b",
    r"\bconflict\b",
    r"\bwar\b",
    r"\btreaty\b",
    r"\bgeopolitic(s)?\b",

    # ==== LAW / MEDICAL / PROFESSIONAL ADVICE ====
    r"\blegal\s+advice\b",
    r"\blawyer\b",
    r"\battorney\b",
    r"\bsue\b",
    r"\bcourt\b",
    r"\bcontract\b",
    r"\bliability\b",
    r"\bmedical\b",
    r"\bdiagnos(e|is)\b",
    r"\btreatment\b",
    r"\btherapy\b",
    r"\bprescription\b",
    r"\bside\s+effect(s)?\b",
    r"\bmental\s+health\b",
    r"\bdoctor\b",
    r"\bclinic\b",
    r"\bpharmacy\b",

    # ==== NUTRITION / FOOD RECIPES ====
    r"\bcalorie(s)?\b",
    r"\bnutrition(al)?\b",
    r"\bprotein\b",
    r"\bcarb(s|ohydrate(s)?)\b",
    r"\bfat(s)?\b",
    r"\bvitamin(s)?\b",
    r"\bmineral(s)?\b",
    r"\brecipe(s)?\b",
    r"\bcook(ing)?\b",
    r"\bbake(ing)?\b",
    r"\bhow\s+to\s+cook\b",
    r"\bingredients?\b",
    r"\bserving(s)?\b",
    r"\bdiet\b",
    r"\bketo\b",
    r"\bvegan\b",
    r"\bvegetarian\b",
    r"\bgluten[-\s]?free\b",

    # ==== PERSONAL DATA / IDENTIFIERS / PRIVACY ====
    r"\bssn\b",
    r"\bsocial\s+security\b",
    r"\bpassport\b",
    r"\bid\s+card\b",
    r"\bdriver'?s?\s+license\b",
    r"\bcredit\s+card\b",
    r"\bdebit\s+card\b",
    r"\bcvv\b",
    r"\bpin\b",
    r"\biban\b",
    r"\bswift\b",
    r"\baddress\b",
    r"\bphone\s+number\b",
    r"\bemail\b",

    # ==== HACKING / CYBERSECURITY / MALWARE ====
    r"\bhack(ing|ers?)?\b",
    r"\bhacker(s)?\b",
    r"\bexploit(s)?\b",
    r"\b0[- ]?day\b",
    r"\bmalware\b",
    r"\bransomware\b",
    r"\bkeylogger\b",
    r"\bphishing\b",
    r"\bddos\b",
    r"\bbrut(e|al)\s*force\b",
    r"\bspoof(ing)?\b",
    r"\bbackdoor\b",
    r"\btrojan\b",
    r"\bvirus\b",

    # ==== VIOLENCE / ILLEGAL GOODS / WEAPONS ====
    r"\bweapon(s)?\b",
    r"\bgun(s)?\b",
    r"\brifle(s)?\b",
    r"\bpistol(s)?\b",
    r"\bammunition\b",
    r"\bknife(s)?\b",
    r"\bexplosive(s)?\b",
    r"\bbomb\b",
    r"\bgrenade\b",
    r"\bsilencer\b",
    r"\bill?egal\b",
    r"\bdrug(s)?\b",
    r"\bnarcotic(s)?\b",
    r"\bcocaine\b",
    r"\bheroin\b",
    r"\bmdma\b",
    r"\bmarijuana\b",
    r"\bcannabis\b",

    # ==== ADULT / SEXUAL CONTENT ====
    r"\bporn(ography)?\b",
    r"\bxxx\b",
    r"\berotic\b",
    r"\bsex\b",
    r"\bnsfw\b",
    r"\bexplicit\b",
    r"\bnude(s)?\b",
    r"\bescort(s)?\b",

    # ==== RELATIONSHIPS / DATING (NON-BOOK ADVICE) ====
    r"\bdating\b",
    r"\brelationship\b",
    r"\bmarriage\b",
    r"\bdivorce\b",
    r"\bhow\s+to\s+ask\s+out\b",
    r"\bpick-?up\s+line(s)?\b",

    # ==== SELF-HELP / THERAPY ADVICE (NON-BOOK) ====
    r"\btherapy\b",
    r"\btherapist\b",
    r"\bcope\b",
    r"\banxiety\b",
    r"\bdepression\b",
    r"\bstress\b",
    r"\bpanic\b",
    r"\bmental\s+health\b",

    # ==== JOBS / CAREER / RESUMES ====
    r"\bresume\b",
    r"\bcv\b",
    r"\bcover\s+letter\b",
    r"\binterview\b",
    r"\bsalary\b",
    r"\bjob(s)?\b",
    r"\bcareer\b",
    r"\bpromotion\b",
    r"\bhire\b",
    r"\bhr\b",

    # ==== TRAVEL / TRANSPORT ====
    r"\bflight(s)?\b",
    r"\bticket(s)?\b",
    r"\bvisa\b",
    r"\bhotel(s)?\b",
    r"\bairbnb\b",
    r"\bitinerary\b",
    r"\btrain(s)?\b",
    r"\bbus(es)?\b",
    r"\btaxi\b",
    r"\buber\b",
    r"\bbolt\b",
    r"\bgas\b",
    r"\bfuel\b",
    r"\bcar\s+rental\b",
    r"\bparking\b",

    # ==== EDUCATION / HOMEWORK (NON-BOOK HELP) ====
    r"\bhomework\b",
    r"\bassignment\b",
    r"\bexam\b",
    r"\bquiz\b",
    r"\btest\b",
    r"\bworksheet\b",
    r"\banswer\s+key\b",
    r"\bsolve\s+this\b",

    # ==== IMAGE / MEDIA PROCESSING ====
    r"\bimage\b",
    r"\bphoto\b",
    r"\bpicture\b",
    r"\bedit\b",
    r"\bfilter\b",
    r"\bvideo\b",
    r"\baudio\b",
    r"\bmp3\b",
    r"\bcompress\b",
    r"\bconvert\s+(?:jpg|jpeg|png|gif|mp4|mp3)\b",

    # ==== SYSTEM / SHELL / FILES ====
    r"\bls\b",
    r"\bdir\b",
    r"\bcd\s+[/\\]",
    r"\bcopy\b",
    r"\bmove\b",
    r"\bdelete\b",
    r"\brm\b",
    r"\bchmod\b",
    r"\bchown\b",
    r"\bmkdir\b",
    r"\btouch\b",
    r"\bedit\b",
    r"\bopen\s+file\b",

    # ==== EMAIL / MESSAGING (NON-BOOK) ====
    r"\bemail\b",
    r"\bcompose\b",
    r"\bwrite\s+an\s+email\b",
    r"\bslack\b",
    r"\bteams\b",
    r"\bwhatsapp\b",
    r"\btelegram\b",
    r"\bmessage\b",

    # ==== FINANCE DOCS / ACCOUNTING ====
    r"\binvoice\b",
    r"\breceipt\b",
    r"\bbalance\s+sheet\b",
    r"\bincome\s+statement\b",
    r"\bprofit\s+and\s+loss\b",
    r"\bbookkeeping\b",

    # ==== RANDOM TASKING / AUTOMATION ====
    r"\bmake\s+me\b",
    r"\bwrite\s+me\b",
    r"\bdo\s+my\b",
    r"\bgenerate\s+(?:a|an)\b(?!\s+book\s+list)",
    r"\bcreate\s+(?:a|an)\b(?!\s+book\s+list)",

    # ==== GAMES / PUZZLES / RIDDLES ====
    r"\briddle(s)?\b",
    r"\bpuzzle(s)?\b",
    r"\bchess\b",
    r"\bwordle\b",
    r"\b sudoku\b",
    r"\btrivia\b",
]